---
swagger: "2.0"
info:
  description: "The Application"
  version: "1.0.0"
  title: "Sample REST Application"
  contact:
    name: "users@cxf.apache.org"
  license:
    name: "Apache 2.0 License"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/services"
paths:
  /account:
    get:
      operationId: "getAccount"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AccountVO"
          headers: {}
    post:
      operationId: "addAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/AccountVO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AccountVO"
          headers: {}
definitions:
  AccountVO:
    type: "object"
    properties:
      accountNumber:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      balance:
        type: "string"
