cxf:
  jaxrs:
    component-scan: true
    classes-scan-packages: com.amol.payments,org.codehaus.jackson.jaxrs

spring:
  application:
    name: spring-cloud-account-service
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true